### ISSUE TITLE
fido-authenticator: authenticatorGetAssertion does not work with hmac-secret extension

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/nitrokey-3-firmware#14]
Trying to use the authenticatorGetAssertion command with the hmac-secret extension causes a CTAP2_ERR_INVALID_CBOR error.

For example using the [`hmac-secret.py`](https://github.com/Yubico/python-fido2/blob/f7f12da9323910901c9759d362eff10d901fee6e/examples/hmac_secret.py) example from `python-fido2`:
```
$ python3 hmac_secret.py 
no pin

Touch your authenticator device now...

New credential created, with the HmacSecret extension.
Authenticate with salt: b'9b17deb11321cdb10b56d8b75c85125a0e5627440892ef067fdd9f052c1ffd22'

Touch your authenticator device now...

Traceback (most recent call last):
 File "/home/robin/reps/python-fido2/fido2/client.py", line 690, in get_assertion
   assertions, used_extensions = self._do_get_assertion(
 File "/home/robin/reps/python-fido2/fido2/client.py", line 754, in _ctap2_get_assertion
   assertions = self.ctap2.get_assertions(
 File "/home/robin/reps/python-fido2/fido2/ctap2/base.py", line 857, in get_assertions
   first = self.get_assertion(*args, **kwargs)
 File "/home/robin/reps/python-fido2/fido2/ctap2/base.py", line 829, in get_assertion
   return self.send_cbor(
 File "/home/robin/reps/python-fido2/fido2/ctap2/base.py", line 675, in send_cbor
   raise CtapError(status)
fido2.ctap.CtapError: CTAP error: 0x12 - INVALID_CBOR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/home/robin/reps/python-fido2/examples/hmac_secret.py", line 113, in <module>
   result = client.get_assertion(
 File "/home/robin/reps/python-fido2/fido2/client.py", line 704, in get_assertion
   raise _ctap2client_err(e)
fido2.client.ClientError: (<ERR.BAD_REQUEST: 2>, CtapError('CTAP error: 0x12 - INVALID_CBOR'))
```

**Comment by robin-nitrokey** [comment]
The problem is that `ctap-types` does not yet support the new pinUvAuthProtocol(0x04) field in the extension data, see https://github.com/solokeys/ctap-types/issues/1.
