### ISSUE TITLE
usbd-ctaphid crashes while handling big message

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/nitrokey-3-firmware#159]
`usbd-ctaphid` crate crashes while handling big message.

Found while executing load tests for oath-app over usb-ip simulation:
- https://github.com/Nitrokey/nitrokey-webcrypt-usbip/commit/db1625f73622277612bd496d34d37c658bab6a86 v0.1-8-gdb1625f

Note: check first, if the affected dependency is not outdated.

<details>

<summary> log </summary>

```rust
thread 'main' panicked at 'range end index 7542 out of range for slice of length 3072', /home/sz/work/webcrypt/webcrypt
-usbip/components/usbd-ctaphid/src/pipe.rs:570:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::slice::index::slice_end_index_len_fail_rt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/slice/index.rs:76:5
   3: core::slice::index::slice_end_index_len_fail
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/slice/index.rs:69:9
   4: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index_mut
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/slice/index.rs:327:13
   5: <core::ops::range::RangeTo<usize> as core::slice::index::SliceIndex<[T]>>::index_mut
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/slice/index.rs:368:9
   6: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/slice/index.rs:30:9
   7: core::array::<impl core::ops::index::IndexMut<I> for [T; N]>::index_mut
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/array/mod.rs:309:9
   8: usbd_ctaphid::pipe::Pipe<Bus>::handle_response
             at ./components/usbd-ctaphid/src/pipe.rs:570:25
   9: <usbd_ctaphid::class::CtapHid<Bus> as usb_device::class::UsbClass<Bus>>::poll
             at ./components/usbd-ctaphid/src/class.rs:199:9
  10: usb_device::device::UsbDevice<B>::poll
             at /home/sz/.cargo/registry/src/github.com-1ecc6299db9ec823/usb-device-0.2.9/src/device.rs:273:21
  11: usbip_simulation::main
             at ./src/bin/main.rs:186:9
  12: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

Edit: note: limiting reply's length avoids sim crash

**Comment by robin-nitrokey** [comment]
The maximum length for messages handled by `usbd-ctaphid` is [`MESSAGE_SIZE = 3072`](https://github.com/Nitrokey/nitrokey-3-firmware/blob/a891a19def61b3f5cd9add3a93b48d3f38e96312/components/usbd-ctaphid/src/constants.rs#L7) while `ctaphid-dispatch` allows up to [7609 bytes](https://github.com/solokeys/ctaphid-dispatch/blob/f8e7aa14fb1bcf80a824305a0d235ec4f4d7ebf3/src/types.rs#L16).  [`Pipe::handle_response`](https://github.com/Nitrokey/nitrokey-3-firmware/blob/a891a19def61b3f5cd9add3a93b48d3f38e96312/components/usbd-ctaphid/src/pipe.rs#L548-L576) fails to ensure that the response returned by the application respects this limit.  It should return `ERR_OTHER` instead.

**Comment by robin-nitrokey** [comment]
This PR avoids the panic and returns an error instead: https://github.com/trussed-dev/usbd-ctaphid/pull/2
