### ISSUE TITLE
random crashes

### ISSUE THREAD

**Issue by primalmotion** [Nitrokey/nitrokey-3-firmware#262]
It seems the nitrokey3 "crashes" pretty often (firmware 1.4). When that happens, clients like gpg, or firefox, or PAM, are just "stuck". sometimes the key returns a card reading error, something nothing. 

Unplugging/repluging fixes the issue. I'm not sure where to pull relevant logs from, but this happens around 3 or 4 times a day while using GPG and FIDO2 function, mostly

**Comment by robin-nitrokey** [comment]
When the problem happens, do you see a change of the LED color?  What is the result of running `nitropy nk3 list` and `nitropy nk3 status` before replugging the device?

**Comment by primalmotion** [comment]
I'll check all of that next time it happens

**Comment by primalmotion** [comment]
Just happened while trying FIDO auth. The led is solid green

```
 nitropy nk3 list
Command line tool to interact with Nitrokey devices 0.4.36
:: 'Nitrokey 3' keys
Critical error:
An unhandled exception occurred
	Exception encountered: CtapError('CTAP error: 0x06 - CHANNEL_BUSY')

--------------------------------------------------------------------------------
Critical error occurred, exiting now
Unexpected? Is this a bug? Would you like to get support/help?
- You can report issues at: https://support.nitrokey.com/
- Writing an e-mail to support@nitrokey.com is also possible
- Please attach the log: '/tmp/nitropy.log.kfjcakxn' with any support/help request!
- Please check if you have udev rules installed: https://docs.nitrokey.com/nitrokey3/linux/firmware-update.html#troubleshooting
```

```
nitropy nk3 status
Command line tool to interact with Nitrokey devices 0.4.36
Critical error:
An unhandled exception occurred
	Exception encountered: CtapError('CTAP error: 0x06 - CHANNEL_BUSY')

--------------------------------------------------------------------------------
Critical error occurred, exiting now
Unexpected? Is this a bug? Would you like to get support/help?
- You can report issues at: https://support.nitrokey.com/
- Writing an e-mail to support@nitrokey.com is also possible
- Please attach the log: '/tmp/nitropy.log.n_r__211' with any support/help request!
- Please check if you have udev rules installed: https://docs.nitrokey.com/nitrokey3/linux/firmware-update.html#troubleshooting
```

**Comment by primalmotion** [comment]
Here's the log the command asks me to paste :)

````
284        INFO pynitrokey.cli Timestamp: 2023-05-08 09:05:50.433152
284        INFO pynitrokey.cli OS: uname_result(system='Linux', node='axion', release='6.3.1-arch1-1', version='#1 SMP PREEMPT_DYNAMIC Mon, 01 May 2023 17:42:39 +0000', machine='x86_64')
284        INFO pynitrokey.cli Python version: 3.11.3
293        INFO pynitrokey.cli pynitrokey version: 0.4.36
293        INFO pynitrokey.cli cryptography version: 40.0.2
294        INFO pynitrokey.cli ecdsa version: 0.18.0
294        INFO pynitrokey.cli fido2 version: 1.1.1
294        INFO pynitrokey.cli pyusb version: 1.2.1
295        INFO pynitrokey.cli spsdk version: 1.8.0
634        INFO  libusbsio Loading SIO library: /usr/lib/python3.11/site-packages/libusbsio/bin/linux_x86_64/libusbsio.so
640        INFO  libusbsio HID enumeration[94575114131280]: initialized
640       DEBUG  libusbsio HID enumeration[94575114131280]: device #0: Nitrokey 3
640       DEBUG  libusbsio HID enumeration[94575114131280]: device #1: Device Management
640       DEBUG  libusbsio HID enumeration[94575114131280]: device #2: Trackpad / Boot
640       DEBUG  libusbsio HID enumeration[94575114131280]: device #3: Actuator
640       DEBUG  libusbsio HID enumeration[94575114131280]: device #4: Accelerometer
640       DEBUG  libusbsio HID enumeration[94575114131280]: device #5: KBD67v2
640       DEBUG  libusbsio HID enumeration[94575114131280]: device #6: KBD67v2
640       DEBUG  libusbsio HID enumeration[94575114131280]: device #7: KBD67v2
640        INFO  libusbsio HID enumeration[94575114131280]: finished, total 8 devices
645       DEBUG fido2.hid.linux Failed opening device /dev/hidraw8
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/fido2/hid/linux.py", line 98, in list_descriptors
    devices.append(get_descriptor(hidraw))
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fido2/hid/linux.py", line 55, in get_descriptor
    with open(path, "rb") as f:
         ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/dev/hidraw8'
704       DEBUG fido2.hid.linux Failed opening device /dev/hidraw6
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/fido2/hid/linux.py", line 98, in list_descriptors
    devices.append(get_descriptor(hidraw))
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fido2/hid/linux.py", line 55, in get_descriptor
    with open(path, "rb") as f:
         ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/dev/hidraw6'
705       DEBUG fido2.hid.linux Failed opening device /dev/hidraw5
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/fido2/hid/linux.py", line 98, in list_descriptors
    devices.append(get_descriptor(hidraw))
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fido2/hid/linux.py", line 55, in get_descriptor
    with open(path, "rb") as f:
         ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/dev/hidraw5'
705       DEBUG fido2.hid.linux Failed opening device /dev/hidraw4
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/fido2/hid/linux.py", line 98, in list_descriptors
    devices.append(get_descriptor(hidraw))
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fido2/hid/linux.py", line 55, in get_descriptor
    with open(path, "rb") as f:
         ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/dev/hidraw4'
705       DEBUG fido2.hid.linux Failed opening device /dev/hidraw3
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/fido2/hid/linux.py", line 98, in list_descriptors
    devices.append(get_descriptor(hidraw))
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fido2/hid/linux.py", line 55, in get_descriptor
    with open(path, "rb") as f:
         ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/dev/hidraw3'
706       DEBUG fido2.hid.linux Failed opening device /dev/hidraw2
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/fido2/hid/linux.py", line 98, in list_descriptors
    devices.append(get_descriptor(hidraw))
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fido2/hid/linux.py", line 55, in get_descriptor
    with open(path, "rb") as f:
         ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/dev/hidraw2'
706       DEBUG fido2.hid.linux Failed opening device /dev/hidraw1
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/fido2/hid/linux.py", line 98, in list_descriptors
    devices.append(get_descriptor(hidraw))
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fido2/hid/linux.py", line 55, in get_descriptor
    with open(path, "rb") as f:
         ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/dev/hidraw1'
722      WARNING pynitrokey.cli An unhandled exception occurred
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pynitrokey/cli/__init__.py", line 129, in main
    nitropy()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/cli/nk3/__init__.py", line 454, in status
    with ctx.connect_device() as device:
         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/cli/nk3/__init__.py", line 80, in connect_device
    device for device in self.list() if isinstance(device, Nitrokey3Device)
                         ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/cli/nk3/__init__.py", line 59, in list
    return list_nk3()
           ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/__init__.py", line 25, in list
    devices.extend(Nitrokey3Device.list())
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/device.py", line 146, in list
    devices.append(Nitrokey3Device(device))
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/device.py", line 73, in __init__
    self.admin.status()
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/admin_app.py", line 71, in status
    reply = self._call(AdminCommand.STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/admin_app.py", line 58, in _call
    return self.device._call(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/device.py", line 133, in _call
    response = self.device.call(command.value, data=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fido2/hid/__init__.py", line 216, in call
    raise CtapError(struct.unpack_from(">B", recv)[0])
fido2.ctap.CtapError: CTAP error: 0x06 - CHANNEL_BUSY
729       DEBUG       root print: Critical error:
729       DEBUG       root print: An unhandled exception occurred
729       ERROR       root CTAP error: 0x06 - CHANNEL_BUSY
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pynitrokey/cli/__init__.py", line 129, in main
    nitropy()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/cli/nk3/__init__.py", line 454, in status
    with ctx.connect_device() as device:
         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/cli/nk3/__init__.py", line 80, in connect_device
    device for device in self.list() if isinstance(device, Nitrokey3Device)
                         ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/cli/nk3/__init__.py", line 59, in list
    return list_nk3()
           ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/__init__.py", line 25, in list
    devices.extend(Nitrokey3Device.list())
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/device.py", line 146, in list
    devices.append(Nitrokey3Device(device))
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/device.py", line 73, in __init__
    self.admin.status()
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/admin_app.py", line 71, in status
    reply = self._call(AdminCommand.STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/admin_app.py", line 58, in _call
    return self.device._call(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/device.py", line 133, in _call
    response = self.device.call(command.value, data=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fido2/hid/__init__.py", line 216, in call
    raise CtapError(struct.unpack_from(">B", recv)[0])
fido2.ctap.CtapError: CTAP error: 0x06 - CHANNEL_BUSY
732       DEBUG       root listing all connected devices:
798       DEBUG       root :: 'Nitrokey FIDO2' keys
798       DEBUG       root :: 'Nitrokey Start' keys:
816       DEBUG       root :: 'Nitrokey 3' keys
820        INFO  libusbsio HID enumeration[94575123659088]: initialized
820       DEBUG  libusbsio HID enumeration[94575123659088]: device #0: Nitrokey 3
820       DEBUG  libusbsio HID enumeration[94575123659088]: device #1: Device Management
820       DEBUG  libusbsio HID enumeration[94575123659088]: device #2: Trackpad / Boot
820       DEBUG  libusbsio HID enumeration[94575123659088]: device #3: Actuator
820       DEBUG  libusbsio HID enumeration[94575123659088]: device #4: Accelerometer
820       DEBUG  libusbsio HID enumeration[94575123659088]: device #5: KBD67v2
820       DEBUG  libusbsio HID enumeration[94575123659088]: device #6: KBD67v2
821       DEBUG  libusbsio HID enumeration[94575123659088]: device #7: KBD67v2
821        INFO  libusbsio HID enumeration[94575123659088]: finished, total 8 devices
894       DEBUG       root Unable to list devices. See log for the details.
894       ERROR       root Unable to list devices
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pynitrokey/cli/__init__.py", line 129, in main
    nitropy()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/cli/nk3/__init__.py", line 454, in status
    with ctx.connect_device() as device:
         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/cli/nk3/__init__.py", line 80, in connect_device
    device for device in self.list() if isinstance(device, Nitrokey3Device)
                         ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/cli/nk3/__init__.py", line 59, in list
    return list_nk3()
           ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/__init__.py", line 25, in list
    devices.extend(Nitrokey3Device.list())
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/device.py", line 146, in list
    devices.append(Nitrokey3Device(device))
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/device.py", line 73, in __init__
    self.admin.status()
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/admin_app.py", line 71, in status
    reply = self._call(AdminCommand.STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/admin_app.py", line 58, in _call
    return self.device._call(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/device.py", line 133, in _call
    response = self.device.call(command.value, data=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fido2/hid/__init__.py", line 216, in call
    raise CtapError(struct.unpack_from(">B", recv)[0])
fido2.ctap.CtapError: CTAP error: 0x06 - CHANNEL_BUSY

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pynitrokey/helpers.py", line 209, in local_critical
    nitropy.commands["list"].callback()
  File "/usr/lib/python3.11/site-packages/pynitrokey/cli/__init__.py", line 113, in list
    _list()
  File "/usr/lib/python3.11/site-packages/pynitrokey/cli/__init__.py", line 106, in _list
    nk3.commands["list"].callback()
  File "/usr/lib/python3.11/site-packages/pynitrokey/cli/nk3/__init__.py", line 138, in list
    for device in list_nk3():
                  ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/__init__.py", line 25, in list
    devices.extend(Nitrokey3Device.list())
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/device.py", line 146, in list
    devices.append(Nitrokey3Device(device))
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/device.py", line 73, in __init__
    self.admin.status()
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/admin_app.py", line 71, in status
    reply = self._call(AdminCommand.STATUS)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/admin_app.py", line 58, in _call
    return self.device._call(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynitrokey/nk3/device.py", line 133, in _call
    response = self.device.call(command.value, data=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fido2/hid/__init__.py", line 216, in call
    raise CtapError(struct.unpack_from(">B", recv)[0])
fido2.ctap.CtapError: CTAP error: 0x06 - CHANNEL_BUSY
900       DEBUG       root print: --------------------------------------------------------------------------------
900       DEBUG       root print: Critical error occurred, exiting now
900       DEBUG       root print: Unexpected? Is this a bug? Would you like to get support/help?
900       DEBUG       root print: - You can report issues at: https://support.nitrokey.com/
900       DEBUG       root print: - Writing an e-mail to support@nitrokey.com is also possible
900       DEBUG       root print: - Please attach the log: '/tmp/nitropy.log.n_r__211' with any support/help request!
900       DEBUG       root print: - Please check if you have udev rules installed: https://docs.nitrokey.com/nitrokey3/linux/firmware-update.html#troubleshooting
````

**Comment by szszszsz** [comment]
> Just happened while trying FIDO auth.

Hi! Can you share which browser do you use?

**Comment by primalmotion** [comment]
Yes, it's FF. What else? :)

**Comment by sosthene-nitrokey** [comment]
Given the `CHANNEL_BUSY` error, I guess it's the same error as https://github.com/Nitrokey/nitrokey-3-firmware/issues/200
